# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gojekyll < Formula
  desc "Go clone of the Jekyll static site generator"
  homepage "https://github.com/reidransom/gojekyll"
  version "1.0.2"
  license "MIT"

  depends_on "dart-sass"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reidransom/gojekyll/releases/download/v1.0.2/gojekyll_Darwin_x86_64v1.tar.gz"
      sha256 "cb0b5ad44e10f348e78b81d4374e9ae7a8819fe3ecfb4df30c6982421b6e07d1"

      define_method(:install) do
        bin.install "gojekyll"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/reidransom/gojekyll/releases/download/v1.0.2/gojekyll_Darwin_arm64.tar.gz"
      sha256 "aeeb39065424cad83f2b427f790d9b0a7083b7a07c7936eec78bce2d53281bf0"

      define_method(:install) do
        bin.install "gojekyll"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/reidransom/gojekyll/releases/download/v1.0.2/gojekyll_Linux_x86_64v1.tar.gz"
      sha256 "a74afac9e72e2773ac95673516b452e66f3f5ef7827986dd27746b31929b2627"
      define_method(:install) do
        bin.install "gojekyll"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/reidransom/gojekyll/releases/download/v1.0.2/gojekyll_Linux_armv6.tar.gz"
      sha256 "a426b537c4c6dc827641f271ad0b412603714ca831bb3536770c896d661d177b"
      define_method(:install) do
        bin.install "gojekyll"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reidransom/gojekyll/releases/download/v1.0.2/gojekyll_Linux_arm64.tar.gz"
      sha256 "b28145b35ad25f72e1518cbe3858018186438ca30363db845a19508a7c311116"
      define_method(:install) do
        bin.install "gojekyll"
      end
    end
  end

  test do
    system "#{bin}/gojekyll", "version"
  end
end
