# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jigyll < Formula
  desc "Go clone of the Jekyll static site generator"
  homepage "https://github.com/reidransom/jigyll"
  version "1.11.1"
  license "MIT"

  depends_on "dart-sass"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reidransom/jigyll/releases/download/v1.11.1/jigyll_Darwin_x86_64v1.tar.gz"
      sha256 "e2ee023910007561833571ad31279db8daa7f308a2502b3594464b205c2a0598"

      define_method(:install) do
        bin.install "jigyll"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/reidransom/jigyll/releases/download/v1.11.1/jigyll_Darwin_arm64.tar.gz"
      sha256 "38fb702afa90ff96fc198f84ea428df0bbfa86fd2bc8371b6d55e01e58201227"

      define_method(:install) do
        bin.install "jigyll"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/reidransom/jigyll/releases/download/v1.11.1/jigyll_Linux_x86_64v1.tar.gz"
      sha256 "1f4842ae0818acd678c76be2165234f2511a0977fd6c4941e48ded078a32c24e"
      define_method(:install) do
        bin.install "jigyll"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/reidransom/jigyll/releases/download/v1.11.1/jigyll_Linux_armv6.tar.gz"
      sha256 "1ed19bd82f5ab628d3c1599d1bff0e3dbe108601cb09c41abae38eda58c78fcf"
      define_method(:install) do
        bin.install "jigyll"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reidransom/jigyll/releases/download/v1.11.1/jigyll_Linux_arm64.tar.gz"
      sha256 "ee8824bbb11390ca1f9fbfeb033abd175a2a92b751f692c48d71461f32d1ad98"
      define_method(:install) do
        bin.install "jigyll"
      end
    end
  end

  test do
    system "#{bin}/jigyll", "version"
  end
end
