# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jigyll < Formula
  desc "Go clone of the Jekyll static site generator"
  homepage "https://github.com/reidransom/jigyll"
  version "1.8.0"
  license "MIT"

  depends_on "dart-sass"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reidransom/jigyll/releases/download/v1.8.0/jigyll_Darwin_x86_64v1.tar.gz"
      sha256 "12d8f2bb76a028768c754727bb757b008bcd6898249eb048d652d74341c5f1ed"

      define_method(:install) do
        bin.install "jigyll"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/reidransom/jigyll/releases/download/v1.8.0/jigyll_Darwin_arm64.tar.gz"
      sha256 "cec154ef2e5d9bf5af91e69c3c65a01e83a6c5e81c9b37be388965e9f9405b48"

      define_method(:install) do
        bin.install "jigyll"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/reidransom/jigyll/releases/download/v1.8.0/jigyll_Linux_x86_64v1.tar.gz"
      sha256 "af65f73334b925ec998161d3f67f854aa118d7ebcea60656c7108e51eb7b5a15"
      define_method(:install) do
        bin.install "jigyll"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/reidransom/jigyll/releases/download/v1.8.0/jigyll_Linux_armv6.tar.gz"
      sha256 "82560e97986c58f831bf7e92251175f4903ab74b48da859522e859b43bdea736"
      define_method(:install) do
        bin.install "jigyll"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reidransom/jigyll/releases/download/v1.8.0/jigyll_Linux_arm64.tar.gz"
      sha256 "8c14bcb5f76ccd8b81626e7fb8cb5e68c2f613d34230ef3c735874b9f85a98f7"
      define_method(:install) do
        bin.install "jigyll"
      end
    end
  end

  test do
    system "#{bin}/jigyll", "version"
  end
end
