# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Servd < Formula
  desc "Run and manage many local dev servers at once."
  homepage "https://github.com/reidransom/servd"
  version "0.1.0-rc.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reidransom/servd/releases/download/v0.1.0-rc.1/servd_Darwin_x86_64.tar.gz"
      sha256 "922cd246badc2b6836f9de3a5407866b9419d9679dc0640841519c927d4b3385"

      define_method(:install) do
        bin.install "servd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/reidransom/servd/releases/download/v0.1.0-rc.1/servd_Darwin_arm64.tar.gz"
      sha256 "8f8162ae409c7d414e9e74e146200cb052661d29a92638a42db8c992315e4cbe"

      define_method(:install) do
        bin.install "servd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/reidransom/servd/releases/download/v0.1.0-rc.1/servd_Linux_x86_64.tar.gz"
      sha256 "77472107b206a1a92c7db365e0e247473973b21a9409a7a4ebf65ba2bb4bec55"
      define_method(:install) do
        bin.install "servd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reidransom/servd/releases/download/v0.1.0-rc.1/servd_Linux_arm64.tar.gz"
      sha256 "14943d43ba7a9ea88a55c1a1786fc2c2b6501ef3bca9dfecd93a012beb00c176"
      define_method(:install) do
        bin.install "servd"
      end
    end
  end

  test do
    system "#{bin}/servd", "version"
  end
end
