# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Servd < Formula
  desc "Run and manage many local dev servers at once."
  homepage "https://github.com/reidransom/servd"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reidransom/servd/releases/download/v0.6.0/servd_Darwin_x86_64.tar.gz"
      sha256 "6a57d30d9b06d0264770a4efce0c559d3d2726e9bf8c2b461de5f5fd5387a826"

      define_method(:install) do
        bin.install "servd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/reidransom/servd/releases/download/v0.6.0/servd_Darwin_arm64.tar.gz"
      sha256 "aa042453e343726b10ff86d87560816f37e251d18462b7d45dcf616760d8bead"

      define_method(:install) do
        bin.install "servd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/reidransom/servd/releases/download/v0.6.0/servd_Linux_x86_64.tar.gz"
      sha256 "46dd9b2852961be12842e801e12aa9a690eafde004b8ef026b4667e6235e10f0"
      define_method(:install) do
        bin.install "servd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reidransom/servd/releases/download/v0.6.0/servd_Linux_arm64.tar.gz"
      sha256 "1495872337d44f1799ee527dd40aee2242ef22335fb11410e2af036c6f1ef90c"
      define_method(:install) do
        bin.install "servd"
      end
    end
  end

  test do
    system "#{bin}/servd", "version"
  end
end
